set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}' SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE ${DATABASE_NAME} owner ${DATABASE_USER};"
