# Generated by Django 5.1.2 on 2024-11-20 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField()),
                ('event_date_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('environment', models.TextField(default='Local')),
                ('event_context', models.TextField()),
            ],
        ),
    ]
